export const seeds = [
  {
    // id: 1,
    // createdAt: "2021-04-16T06:51:41.000Z",
    // updatedAt: "2021-04-16T06:51:41.000Z",
    userName: "ibnu",
    lastDomain: null,
    email: "ibnu.kamal@similie.org",
    phone: null,
    secondaryEmail: null,
    secondaryPhone: null,
    dob: null,
    title: "Software Developer",
    firstName: "Ibnu",
    middleName: null,
    lastName: "Kamal",
    role: 9,
    siteRole: 9,
    preferredLanguage: null,
    online: false,
    active: true,
    archive: false,
    requestor: 2,
    sessionKey: "3804d4d6-5ced-4ac6-8ac9-d06be0f0a93c",
    apiSession: null,
    apiKey: "/uy1ZikkWTXFGI9pCrSMHvSnto4EJfzITjFcll20WWMXpa7IYU+ZHuYDEaHW9LGH",
    avatar: null,
    rankBadge: null,
    organization: null,
    sounds: true,
    employeeId: null,
    stateKey: 2648,
    forceReset: false,
    schema: null,
    primaryDistrict: null,
    meta: { clear_language: true },
    personnel: false,
    userAccessDisabled: false,
    enlistementDate: null,
    primaryStationRoute: false,
    specialty: null,
    trade: null,
    styleMode: null,
    ldapEnabled: false,
  },

  {
    // id: 2,
    // createdAt: "2021-04-16T06:51:41.000Z",
    // updatedAt: "2021-04-16T06:51:41.000Z",
    userName: "guernica0131",
    lastDomain: null,
    email: "info@similie.org",
    phone: null,
    secondaryEmail: null,
    secondaryPhone: null,
    dob: null,
    title: "Software Developer",
    firstName: "Code",
    middleName: null,
    lastName: "King",
    role: 5,
    siteRole: 9,
    preferredLanguage: null,
    online: false,
    active: true,
    archive: false,
    requestor: 1,
    sessionKey: "3804d4d6-5ced-4ac6-8ac9-d06be0f0a93d",
    apiSession: null,
    apiKey: "/uy1ZikkWTXFGI9pCrSMHvSnto4EJfzITjFcll20WWMXpa7IYU+ZHuYDEaHW9LGM",
    avatar: null,
    rankBadge: null,
    organization: null,
    sounds: true,
    employeeId: null,
    stateKey: 2649,
    forceReset: false,
    schema: null,
    primaryDistrict: null,
    meta: { clear_language: true },
    personnel: false,
    userAccessDisabled: false,
    enlistementDate: null,
    primaryStationRoute: false,
    specialty: null,
    trade: null,
    styleMode: null,
    ldapEnabled: false,
  },
];
